
version: "3.7"
services:
  app:
    build:
      args:
        user: johnydelson
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: myapp
    container_name: myapp
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - network-myapp

  #POSTGRES
  db:
    image: postgres:13.0
    container_name: myapp-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: myapp
    volumes:
      - ./docker-compose/postgres:/var/lib/postgresql/data
    ports:
      - 5434:5432
    networks:
     - network-myapp
  
  #MYSQL
  #db:
  #  image: mysql
  #  container_name: myapp-db
  #  restart: unless-stopped
  #  environment:
  #    MYSQL_DATABASE: ${DB_DATABASE}
  #    MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #    SERVICE_TAGS: dev
  #    SERVICE_NAME: myapp
  #  volumes:
  #    - ./docker-compose/mysql:/var/lib/mysql
  #  ports:
  #    - 3307:3306
  #  networks:
  #    - network-myapp

  nginx:
    image: nginx:alpine
    container_name: myapp-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - network-myapp
            
networks:
  network-myapp:
    driver: bridge
